-- MySQL Script generated by MySQL Workbench
-- Tue Jun 11 01:19:45 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema agrocultivasolucoes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema agrocultivasolucoes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agrocultivasolucoes` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `agrocultivasolucoes` ;

-- -----------------------------------------------------
-- Table `agrocultivasolucoes`.`tbUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrocultivasolucoes`.`tbUsuario` (
  `idUsuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(150) NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `senha` VARCHAR(150) NOT NULL,
  `administrador` TINYINT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `id_usuario_UNIQUE` (`idUsuario` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `agrocultivasolucoes`.`tbSafra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrocultivasolucoes`.`tbSafra` (
  `idSafra` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomeSafra` VARCHAR(150) NOT NULL,
  `tipoSafra` VARCHAR(150) NOT NULL,
  `descricao` TEXT NULL,
  PRIMARY KEY (`idSafra`),
  UNIQUE INDEX `id_safra_UNIQUE` (`idSafra` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agrocultivasolucoes`.`tbPesticida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrocultivasolucoes`.`tbPesticida` (
  `idPesticida` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomePesticida` VARCHAR(100) NOT NULL,
  `tipoPesticida` VARCHAR(100) NOT NULL,
  `descricao` TEXT NULL,
  PRIMARY KEY (`idPesticida`),
  UNIQUE INDEX `id_pesticida_UNIQUE` (`idPesticida` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agrocultivasolucoes`.`tbFertilizante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrocultivasolucoes`.`tbFertilizante` (
  `idFertilizante` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomeFertilizante` VARCHAR(100) NOT NULL,
  `tipoFertilizante` VARCHAR(100) NOT NULL COMMENT 'adubo orgânico, composto...',
  `descricao` TEXT NULL,
  PRIMARY KEY (`idFertilizante`),
  UNIQUE INDEX `id_fertilizante_natural_UNIQUE` (`idFertilizante` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agrocultivasolucoes`.`tbAtividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrocultivasolucoes`.`tbAtividades` (
  `idAtividade` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idUsuario` INT UNSIGNED NOT NULL,
  `idSafra` INT UNSIGNED NOT NULL,
  `idPesticida` INT UNSIGNED NULL,
  `idFertilizante` INT UNSIGNED NULL,
  `tipo` VARCHAR(100) NOT NULL COMMENT 'ex (plantio, irrigação, colheita, pesticida...)',
  `qtdd` DOUBLE NOT NULL,
  `dataAtividade` DATETIME NOT NULL,
  `descricao` TEXT NULL,
  PRIMARY KEY (`idAtividade`),
  UNIQUE INDEX `id_atividade_UNIQUE` (`idAtividade` ASC) VISIBLE,
  UNIQUE INDEX `id_pesticida_UNIQUE` (`idPesticida` ASC) VISIBLE,
  INDEX `fk_atividades_users1_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_tbAtividades_tbSafra1_idx` (`idSafra` ASC) VISIBLE,
  CONSTRAINT `fk_atividades_pesticidas`
    FOREIGN KEY (`idPesticida`)
    REFERENCES `agrocultivasolucoes`.`tbPesticida` (`idPesticida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atividades_fertilizantes_naturais`
    FOREIGN KEY (`idFertilizante`)
    REFERENCES `agrocultivasolucoes`.`tbFertilizante` (`idFertilizante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atividades_users1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `agrocultivasolucoes`.`tbUsuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbAtividades_tbSafra1`
    FOREIGN KEY (`idSafra`)
    REFERENCES `agrocultivasolucoes`.`tbSafra` (`idSafra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agrocultivasolucoes`.`tbEstoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrocultivasolucoes`.`tbEstoque` (
  `idEstoque` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idSafra` INT UNSIGNED NULL,
  `idPesticida` INT UNSIGNED NULL,
  `idFertilizante` INT UNSIGNED NULL,
  `nome` VARCHAR(150) NOT NULL,
  `quantidade` DECIMAL(10,2) NOT NULL COMMENT 'quantidade do produto',
  `preco` DECIMAL(10,2) NOT NULL COMMENT 'unidade de medida (kg)',
  `data_entrada` DATE NULL,
  `data_saida` DATE NULL,
  `descricao` TEXT NULL,
  PRIMARY KEY (`idEstoque`),
  UNIQUE INDEX `id_desempenho_UNIQUE` (`idEstoque` ASC) VISIBLE,
  INDEX `fk_tbEstoque_tbPesticida1_idx` (`idPesticida` ASC) VISIBLE,
  UNIQUE INDEX `tbPesticida_idPesticida_UNIQUE` (`idPesticida` ASC) VISIBLE,
  INDEX `fk_tbEstoque_tbFertilizante1_idx` (`idFertilizante` ASC) VISIBLE,
  UNIQUE INDEX `idFertilizante_UNIQUE` (`idFertilizante` ASC) VISIBLE,
  INDEX `fk_tbEstoque_tbSafra1_idx` (`idSafra` ASC) VISIBLE,
  CONSTRAINT `fk_tbEstoque_tbPesticida1`
    FOREIGN KEY (`idPesticida`)
    REFERENCES `agrocultivasolucoes`.`tbPesticida` (`idPesticida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbEstoque_tbFertilizante1`
    FOREIGN KEY (`idFertilizante`)
    REFERENCES `agrocultivasolucoes`.`tbFertilizante` (`idFertilizante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbEstoque_tbSafra1`
    FOREIGN KEY (`idSafra`)
    REFERENCES `agrocultivasolucoes`.`tbSafra` (`idSafra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agrocultivasolucoes`.`tbClima`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrocultivasolucoes`.`tbClima` (
  `idClima` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idSafra` INT UNSIGNED NOT NULL,
  `clima` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `temperatura` FLOAT NOT NULL,
  `descricao` TEXT NOT NULL,
  PRIMARY KEY (`idClima`),
  UNIQUE INDEX `id_condicao_climatica_UNIQUE` (`idClima` ASC) VISIBLE,
  INDEX `fk_condicoes_climaticas_safras1_idx` (`idSafra` ASC) VISIBLE,
  CONSTRAINT `fk_condicoes_climaticas_safras1`
    FOREIGN KEY (`idSafra`)
    REFERENCES `agrocultivasolucoes`.`tbSafra` (`idSafra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
